Simple backup system for Linux users who use ~emacs~ a lot.

* Requirements
1. =emacs=, =mktemp=, =tar=, =gpg= (all available from standard linux packages),
2. elisp part of my [[https://github.com/chalaev/lisp-goodies][lisp-goodies]] project, and
3. [[https://github.com/chalaev/lisp-goodies/blob/master/packaged/batch-start.el][~/.emacs.d/batch-start.el]] (needed for =emacsclient= called in [[file:el-backup][el-backup]]).

* Quick Start
1. Examine [[file:el-backup][el-backup]] and [[file:common.sh][common.sh]] (both supposed to run with root privileges).\\
   Create =/usr/local/bin/el-backup/= and copy [[file:el-backup][el-backup]] and [[file:common.sh][common.sh]] there.
2. Create =/etc/el-backup/= and copy [[file:secret.conf][secret.conf]] and [[file:public.conf][public.conf]] there.
   Edit global configuration files in =/etc/el-backup/=. Ensure that only ~root~ can read =/etc/el-backup/secret.conf=
   and that non-root users are allowed to read  =/etc/el-backup/public.conf=.
3. For each user enumerated in =/etc/el-backup/secret.conf=, copy [[file:el-backup.conf][el-backup.conf]] to =~/.emacs.d/conf/el-backup.conf=
   and edit it.
4. Create group ~tmp~; the code uses it to mark temporary files.
5. Copy [[file:packaged/backup.el][packaged/backup.el]] to =~/.emacs.d/local-packages/=.
   ([[https://github.com/chalaev/lisp-goodies/blob/master/packaged/batch-start.el][~/.emacs.d/batch-start.el]] will configure emacs to load [[file:packaged/backup.el][backup.el]] from there.)
6. Run [[file:el-backup][/usr/local/bin/el-backup/el-backup]] daily with root privileges.
   This will create files =X-Y-Z.tar.bz2= and =X-Y-Z/user.list.gz= (locally on your computer) where X, Y, Z are non-negative integers.
   Their encrypted copies in remote directory will be =X-Y-Z.gpg= and =X-Y-Z.user.gpg=

* Backup philosophy
Only recently modified (later than the previous backup) files will be archived.
By default non-text files are ignored; still binary files can be archived if
- they have "white" extension, or
- their group is "white", or
- their (base) name  is "white".

"White", "grey", and "black" lists can be configured in  [[file:el-backup.conf][~/.emacs.d/conf/el-backup.conf]].

There is no special command to restore the files; the user is supposed to do it manually. Here is my way to do it:
1. Decide if I prefer to use local of remote (encrypted) backup files.
2. With =zgrep= utility, find the file in the list of archived files. Locate the archive with this file.
3. If needed, decrypt the archive. Extract the file from the =tar= archive.

* Files
1. [[file:backup.org][backup.org]] – contains elisp-part of the backup code, which is responsible for user-owned files,
2. [[file:el-backup][el-backup]] is supposed to be run from ~/etc/cron.daily/~  by ~root~ user; it uses the code from
3. [[file:common.sh][common.sh]] updates contents file; this file (containing names of the files to be archived) will be then used by =tar=,
4. [[file:Makefile][Makefile]] to =make= them all,
5. [[file:packaged/backup.el][packaged/backup.el]] for those who do not want to =make=. It should be copied to =~/.emacs.d/local-packages/= or another a directory from where emacs can load it using
   either =emacsclient= or =emacs= command in [[file:el-backup][el-backup]].
6. [[file:secret.conf][secret.conf]] and [[file:public.conf][public.conf]] are (examples of) system configuration files, see Quick Start above.
7. [[file:el-backup.conf][el-backup.conf]] is the user configuration file which is processed by the [[file:packaged/backup.el][eLisp code]].
* License
This code is released under [[https://mit-license.org/][MIT license]].
